OCR-D/ocrd_all

- .gitmodules
https://github.com/mjenckel/LAYoutERkennung
https://github.com/ASVLeipzig/cor-asv-fst
https://github.com/OCR-D/ocrd_im6convert
https://github.com/seuretm/ocrd_typegroups_classifier
https://github.com/ocr-d-modul-2-segmentierung/segmentation-runner
> Add more OCR-D module projects

- Makefile
> Default to make help

- Makefile
> fix f8af582: avoid shared build rule (only share recipe)

- Makefile
> Don't add opencv-python to OCRD_MODULES by default

- .gitignore
- Makefile
> Move tesseract/build to $(VIRTUAL_ENV)/build/tesseract

- Makefile
> Update ocrd_olena and move ocrd_olena/repo/olena/build to build/ocrd_olena

- Makefile
> Fix ownership for files in .git after `sudo make deps-ubuntu`

- .gitmodules
> Update URL for submodule ocrd_pagetopdf

- Makefile
> Support user provided PKG_CONFIG_PATH

- Makefile
- README.md
> Add build rules for Tesseract training tools

- .gitmodules
- CHANGELOG.md
- Makefile
- README.md
This gives:
- ocrd-preprocess-image
- ocrd-skimage-normalize
- ocrd-skimage-denoise-raw
- ocrd-skimage-binarize
- ocrd-skimage-denoise
> add ocrd_wrap

- Makefile
- README.md
Fixes #123 
@stweil please test this, too!
> synchronize concurrent git submodule actions via mutex

- Makefile
Just a hunch that this might be the issue.
> apt-get update before apt-get install, fix #133

- README.md
> Fix documentation of Docker command (#143)

- Makefile
> Update names of processors for ocrd_cis and ocrd_fileformat

- Makefile
The error message looks better without it.
> Suppress stderr when checking for sem / wget / curl

- Dockerfile
> docker: don't clean venvs in -git prebuilds

- Makefile
> deps-ubuntu: fix 7ada73be35 (chown all OCRD_MODULES)

- Makefile
> emulate file function in make<4.0

- .github/contributing.md
> Fix typo in documentation

- CHANGELOG.md
- release.sh
@stweil Can/should we update tesseract to master?
> :package: v2021-02-27

- CHANGELOG.md
- Makefile
Updates core, includes #269 and #261
> Update 2021 11 30

- Makefile
> Update apt package list before trying to install packages

- Makefile
> Replace PIP macro by simple pip

- Makefile
Fixes: 99ee99fe10a4f03c (:package: v2022-03-25)
> Fix build rule for ocrd_anybaseocr

- .circleci/config.yml
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034.
> CircleCI: Replace legacy by next-gen convenience images

- .github/workflows/makedocker.yml
> Create alias image 'latest' for docker image 'maximum-git'

- .github/workflows/makeall.yml
> Add build on Ubuntu 22.04 to GitHub action

- Makefile
> Remove useless commands in Makefile

- release.sh
> release.sh: Update help text

- .gitmodules
- Makefile
- README.md
Dependencies are tiny, so medium should fit.
> Add docstruct

- .gitmodules
- Makefile
- README.md
This PR introduces two new processors, `ocrd-neat-export` and `ocrd-neat-import`.
These allow converting PAGE-XML to [neat](https://github.com/qurator-spk/neat) TSV (`ocrd-neat-export`) and neat TSV results back into PAGE-XML (`ocrd-neat-import`).
neat is an annotation tool originally developed for NER/NEL tasks, but adapted to be used for producing/correcting line-based Ground Truth for training OCR engines. It's a simple HTML+Javascript application that requires no additional libraries and can be used offline in any browser.
A typical workflow for GT creation with neat:
1. `ocrd-eynollah-segment` or any other [segmentation processor](https://ocr-d.de/en/workflows#layout-analysis) for the line segmentation
2. Optionally: [`ocrd-*-recognize`](https://ocr-d.de/en/workflows#text-recognition) …
> Add ocrd_neat

- Makefile
> Only run pip check once per virtual environment

- .github/workflows/makeall.yml
- Dockerfile
> Remove Ubuntu 18.04 from configurations and documentation

- .dockerignore
- .gitignore
- Dockerfile
- Makefile
- README.md
- ocrd-all-module-dir.py
- ocrd-all-tool.py
> Docker fix tesseract module location

- .gitmodules
- Makefile
https://github.com/OCR-D/ocrd_froc/ is the successor to https://github.com/OCR-D/ocrd_typegroups_classifier/
It supports classifiying font used in `pc:TextLine` and annotating that as `pc:TextStyle`.
Besides, it also supports text recognition with different implementations.
It still needs some work, notably unit tests and proper handling of resources, but it is self-contained and offers unique functionality and significantly improves upon typegroups_classifier, so I think it's time to make it available to users.
> replace ocrd_typegroups_classifier with ocrd_froc

- Makefile
> Fix pip check and some native configurations

- .gitmodules
- Makefile
Neither of these are actively maintained and probably not worth porting to v3 or even keeping in ocrd_all.
> Drop ocrd_repair_inconsistencies and ocrd_pc_segmentation
