OCR-D/ocrd_all

.gitmodules, Makefile
Use OCR-D forks of LAYoutERkennung and typegroups_classifier. We publish PyPI packages from them and they allow us more rapid development.
(this can wait until repo transfer)
=> Ocrd forks

Makefile
This converts rules that specify multiple targets with a recipe that builds them all at once – as most multi-executable modules have – into pattern rules, so `make` "knows" that all the targets are built together. Thus, the rule only fires once per module (instead of once per executable), and parallel building (`make -j`) becomes possible again. 
We could have waited for GNU make 4.2 for this, which finally added new syntax to support such rule semantics (via `:&` instead of `:`). But pattern rules can do this, too. They are just more difficult to read and write.
(I encapsulated this in a parameterized function `multirule` which takes the original list of executables and replaces the `$(BIN)/` part – which is _assumed_ to always be present – with `%`, so the rule becomes a pattern rule, …
=> convert multi-output recipes to pattern rules to avoid repetition

Makefile
Otherwise I get a build failure for `make ocrd-tesserocr-binarize` with a newly created venv.
=> mkdir -p sharedir before touch

.gitmodules, Makefile
c.f. https://github.com/qurator-spk/ocrd_repair_inconsistencies/issues/2
=> Add https://github.com/qurator-spk/ocrd_repair_inconsistencies

.circleci/config.yml, Dockerfile, Makefile
<del>still tweaking, pls ignore for now
It is working now. Building medium and maximum takes about 20 minutes each, publishing to Docker Hub about 5 minutes, c.f. https://circleci.com/gh/OCR-D/ocrd_all/7.
Images are named
- `ocrd/all:minimum`
- `ocrd/all:medium`
- `ocrd/all:maximum`
Every push to master will now trigger rebuilding and updating images.
=> docker deployment

Makefile
That should suffice to at least install cor-asv-fst properly. (It still does not make it [usable](https://github.com/ASVLeipzig/cor-asv-fst/blob/a0bc5f9f5196050c4c53ca58d0588aa42aaa1422/ocrd_cor_asv_fst/wrapper/decode.py#L237) though... so let's keep it deactivated here.)
=> cor-asv-fst: fix build

Makefile, README.md
This implements @stweil's proposed `DISABLED_MODULES` and disables ocrd_kraken, clstm and ocrd_ocropy. That way, they are still present for the more curious and brave user but won't be installed by default.
=> DISABLED_MODULES, disable ocrd_kraken, clstm and ocrd_ocropy, fix #11, fix #21

Makefile
Without redirection support curl downloads HTML code instead of the desired traineddata.
=> Use curl with -L option (follow redirect)

Makefile
=> Add rule for page2img

.circleci/config.yml
Since we don't run `deploy` on PR branches, do we have a chance to test whether this actually works _before_ merging?
=> CircleCI: run docker pushs in parallel but with steady stdout

Dockerfile
To process large Images, like newspaper pages, the current ImageMagick defaults are insufficient.
They result into errors like this when used with modules like `ocrd_im6convert`or `ocrd_olena`:
```
+ docker run -u 1000 -w /data -v /home/m3ssman/Projects/ulb/ulb-dd-ocr-eval-ocrd/ocrd-work:/data -v /usr/share/tesseract-ocr/4.00/tessdata:/usr/local/share/tessdata/ ocrd/all:medium ocrd-make -f ulb-ocrd-newspaper.mk .
make: Entering directory '/data'
make -R -C . -I /data/ -f /data/ulb-ocrd-newspaper.mk  2>&1 | tee ..ulb-ocrd-newspaper.log
make[1]: Entering directory '/data'
building OCR-D-BINPAGE-sauvola from MAX with pattern rule for ocrd-olena-binarize
ocrd workspace remove-group -r OCR-D-BINPAGE-sauvola 2>/dev/null || true
ocrd-olena-binarize -I MAX -O OCR-D-BINPAGE-sauvola -p …
```
=> [app][fix] prevent imagemagick cache exhausted

Makefile
As discussed in UB-Mannheim/ocrd_pagetopdf#12 (Better wait for that one to get merged before merging this).
=> Makefile: Add deps-ubuntu rule for ocrd_pagetopdf submodule

Makefile
Model wasn't bundled because of https://github.com/ocr-d-modul-2-segmentierung/ocrd-pixelclassifier-segmentation/issues/10#issuecomment-630676588
=> Update ocrd-pixelclassifier-segmentation -> 0.1.5

CHANGELOG.md
Update:
* `ocrd_olena`: e000f24 (1.1.7)
* `tesseract`: 62eae84
* `ocrd_cis`: a6a2ecd
* `ocrd_tesserocr`: 9d2253e (0.8.3 +1)
* `sbb_textline_detector`: 3593506
* `workflow-configuration`: 403ef75
Added:
* `CHANGELOG.md` to track changes
=> Update ocrd_olena, tesseract, ocrd_cis

.circleci/config.yml, .github/contributing.md, LICENSE, README.md, release.sh
1. Create a new branch with any name, e.g. `git checkout -b update-$(date +'%Y-%m-%d')`
2. Selectively update submodules in a way that makes sense to you. To upgrade
all submodules to the latest upstream versions, run `./release.sh update`. To
update only a specific submodule, such as `ocrd_cis`, run `./release.sh update
ocrd_cis`. Or update individual submodules manually: `cd <submodule>; git pull
origin master` (replace `master` if you want to merge another branch instead)
3. Manually check with `git status` that the changes are consistent with what
you want to update in the PR.
4. `git add` / `git commit`
5. `git push` to your `ocrd_all` fork on GitHub
6. Open a new PR for that branch (The `git push` request will show you the right URL)
1. Wait for CI to successfully finish (ensuring …
=> add release.sh script to generate changelog, release to GH and Dockerhub

Makefile
(old recipe does not work anymore, we now
have TF2 as `tensorflow` and TF1 as `tensorflow-gpu`)
Fix #114
=> Makefile: fix fix-pip rule for Tensorflow

release.sh
...as this is now the default branch again.
=> release.sh: use master instead of dev on ocrd_cis

Makefile, README.md
Fix #127 
As [discussed](https://github.com/OCR-D/ocrd_all/issues/127#issuecomment-659358910), this allows building Tesseract in other ways (including the static/shared decision etc).
=> expose variable for Tesseract configure params

CHANGELOG.md, Makefile
Adds targets `install-models{,-tesseract,-ocropy,-calamari}` to install recognition models by @stweil, @mikegerber, @jze, @chreul to sensible locations in `$(VIRTUAL_ENV)/share`.
The list of installed models is far from exhaustive and can/should be easily amended. 
This is a stopgap solution until we have a proper model repository. I had to re-download models over the last two weeks for different environments and I thought I might as well create a script and `ocrd_all` seemed like a good place.
I tried to use GitHub locations where possible. If potential traffic spikes from adding model download here are of concern, I can set up a mirror.
=> make install-models to install commonly used models for tesseract, ocropy, calamari

Makefile
Will merge this quickly because the problem is not triggered in the PR build. I'll keep #133 open though so we can find a better solution. But for now, I want the docker images building again ASAP.
=> :fire: exclude tesseract-ocr-equ from CUSTOM_DEPS, fix #133

Dockerfile, Makefile, README.md
=> Fix sub-venv

Makefile
It is not needed when a pre-installed Tesseract is used.
=> Model dependency of tesserocr on tesseract

Makefile
Running autogen.sh creates a new configure file. That updates the timestamp for tesseract.
With the dependency introduced in commit e1b30b95, that triggered a new run of autogen.sh
when make was run again and so on.
=> Avoid repeated Tesseract builds

.circleci/config.yml, Dockerfile, Makefile
Once we merge https://github.com/OCR-D/core/pull/454, there will be an additional `ocrd/core-cuda` base image based on [nvidia/cuda:11.0-base-ubuntu18.04](https://hub.docker.com/layers/nvidia/cuda/11.0-base-ubuntu18.04/images/sha256-d2ad87954a40fa4671e81df1fac5989448323bfa846ced05898058b1805b3723?context=explore). We can then create CUDA-capable variants of ocrd_all Docker images.
We'll need to investigate parallelization for the CI/CD because otherwise this will double the build time.
=> support Docker additional variants based on ocrd/core-cuda

release.sh
This avoids a warning from git:
warning: Pulling without specifying how to reconcile divergent branches is
discouraged.
=> Update release.sh to use git pull --rebase

.circleci/config.yml
(I wonder why this could have ever worked before. I was only alerted to this by [a recent failure](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/371/workflows/1704573c-c4eb-4780-af4c-313d89a1930c/jobs/371), which should not have occured that way either...)
Also, I don't understand why CircleCI's "restart from failed" does not restart from the failed step, but repeats the whole job.
Anyway, be warned I cannot test this outside of the CI, so expect a total breakdown!
=> CircleCI deploy parallel push: terminate after last job

Makefile
<del>This should ensure that core is installed first for every module.</del>
It's ridiculously inefficient, not even sure if this ever finishes :fire:
=> Add $(BIN)/ocrd as order-only target to install first

release.sh
Don't fail if there exist branches which have the same names as some submodules.
=> Make release.sh more robust

Makefile
The setup.py script fails to build opencv-python when it is run from a
different directory:
. /venv-20201008/bin/activate && ENABLE_HEADLESS=1 python3 opencv-python/setup.py bdist_wheel
Traceback (most recent call last):
File "opencv-python/setup.py", line 448, in <module>
main()
File "opencv-python/setup.py", line 57, in main
build_contrib, build_headless, is_CI_build
File "opencv-python/setup.py", line 417, in get_and_set_info
with open(version_file) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/ocrd_all/opencv-python/opencv-python/cv2/version.py'
Makefile:187: recipe for target '/venv-20201008/share/opencv-python' failed
make: *** [/venv-20201008/share/opencv-python] Error 1
Fix this by changing the directory before starting the script.
Signed-off-by: Stefan Weil …
=> Fix build for opencv-python

Dockerfile, Makefile
This removes the irritating situation that all executables from sub-venvs end up in /usr/local/bin whereas the others are in /usr/bin (which also makes it more difficult for dependent stages to add their scripts).
=> Docker prefix path

Makefile
Such additional options might be unsupported by the old pip version.
=> Don't use additional pip options for pip upgrade

Makefile
It was not upgraded for an existing venv.
=> Make sure that pip always gets upgraded

Dockerfile
As discussed in https://github.com/OCR-D/ocrd_calamari/issues/46#issuecomment-711053497, the Dockerfile currently omits a number of important environmental variables: `LC_ALL`, `LANG`, and `TF_FORCE_GPU_ALLOW_GROWTH`.
Unless the `LC_ALL` and `LANG` environmental variables are configured on the host device to use Unicode, running Python in the produced Docker image fails with the following error:
```
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:
export LC_ALL=C.UTF-8
export …
```
=> Add LC_ALL, LANG, and TF_FORCE_GPU_ALLOW_GROWTH ENVs to Dockerfile

.gitmodules, Makefile
> Pixelwise binarization with selectional auto-encoders in Keras
@jbarth-ubhd has an example of the result in https://github.com/OCR-D/ocrd-website/issues/172#issuecomment-708416972
=> add qurator-spk/sbb_binarization

Makefile
This fixes a problem I've overlooked initially: Having the `ocrd` (or core) dependency above the `MAKELEVEL` distinction, i.e. visible both on the inner and outer invocation, is not only unnecessary (as the outer rules strictly only need a bash script), but may _break_ when the outer venv is not fully installed already (which may even happen on an initial checkout when running `make -j all`). Example:
```
make ocrd-anybaseocr-crop -W core
. /tmp/ocrd_all/venv/local/sub-venv/headless-tf21/bin/activate && make -C core install PIP_INSTALL="pip3 install "
/bin/sh: 1: .: Can't open /tmp/ocrd_all/venv/local/sub-venv/headless-tf21/bin/activate
Makefile:162: recipe for target '/tmp/ocrd_all/venv/bin/ocrd' failed
```
Explanation: the outer `$(BIN)/ocrd` rule gets checked for dependencies in a …
=> sub-venv rules: move core dependency to inner make exclusively

Makefile
The VIRTUAL_ENV is also passed to each recursive make, so to get the right
sub venvs it must be changed explicitly for the recursive calls.
Signed-off-by: Stefan Weil <sw@weil.de>
=> Fix make VIRTUAL_ENV=PATH (issue #228)

.dockerignore, Dockerfile, Makefile, README.md
This brings `make check`:
- verify all `OCRD_EXECUTABLES` are executable from their venvs (for sub-venv modules: both the outer delegator and the inner Python script)
- optionally (`CHECK_HELP=1`) also try to _run_ them with `--help` or `-h` (currently only does not work for `typegroups-classifier`)
- do `pip check` (for sub-venv modules, _also inside_)
If anyone has an idea how to do the latter (the sub-venv `pip check`) without the extra 2 lines in each respective ruleset, then please let me know.
=> Add checks

Dockerfile, Makefile
Once OCR-D/core#559 is merged.
=> make install-models: delegate to ocrd resmgr

Dockerfile
@kba, https://github.com/OCR-D/ocrd_all/commit/2fdce0a872638d16e8afe9cc2d23ebc9168b0568#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R36 was actually detrimental to our idea. See comments in the change itself for exlanation.
=> Dockerfile: disable volume for resources

Makefile
Not sure if this is the right way to do it (`make` phase 1 cannot be used to check `ocrd bashlib constants XDG_DATA_HOME` etc, but `install` recipes already use `ocrd resmgr download`, so maybe we should _export_ `XDG_DATA_HOME` defined here...). 
But the current state is clearly broken: minimal models will only be installed into `venv/share/tessdata`, where models are usable for standalone Tesseract without `--tessdata-dir`, but not for our wrapper – it now expects them in `$XDG_DATA_HOME/ocrd-resources/ocrd-tesserocr-recognize` (and there is nothing besides setting the environment variable override `export TESSDATA_PREFIX=$VIRTUAL_ENV/share/tessdata` that could save that).
=> adapt TESSDATA to resmgr default

.gitmodules, CHANGELOG.md, Makefile
Adds a processor `ocrd-eynollah-segment` wrapping the segmentation/reading-order detection tool https://github.com/qurator-spk/eynollah by @vahidrezanezhad.
Also updates OCR-D/core to 2.23.3 which makes the default set of models installable via `ocrd resmgr download ocrd-eynollah-segment default`.
=> add eynollah

CHANGELOG.md
This fixes the namespace conflict between sbb_textline_detection and eynollah that broke the docker builds.
Also fixes some problems in eynollah.
=> :package: v2021-05-04

Makefile
- Remove development packages for graphic libraries which are not required
- Add missing development packages
- Add required package for training tools
=> Fix dependencies for Tesseract (fix issue #259)

Makefile
To prevent pc_segmentation from dragging in TF 2.5 and thus invalidating that venv for other modules.
=> update ocrd_pc_segmentation, move from tf21 to tf2

Makefile
This allows using the `tesseract` cli again without setting an
explicit TESSDATA_PREFIX.
=> Don't disable built-in TESSDATA_PREFIX

Dockerfile
=> Docker: multi-version CUDA

Makefile
Pursuant to #286, try using the same mechanism we already use for `git` to bring about isolation for `pip` as well – but allow different venvs to be modified concurrently.
Also contains an attempt at speeding up build by replacing the costly re-pip trick (forcing reinstallation to ensure up-to-date timestamps) with just direct timestamp update (but for the targets only).
=> isolate pip with venv semaphores

.github/workflows/makeall-linux.yaml, .github/workflows/makeall.yml
It is currently configured to be triggered manually either from the
GitHub web frontend or from the GitHub API.
`make all` can be run with a selected version of Ubuntu and Python,
or a matrix of versions.
=> Add GitHub action for `make all`

Makefile
It is used for special handling of several versions of Python,
here to disable ocrd_kraken with Python 3.10.
=> Add new macro PYTHON_VERSION

.circleci/config.yml, Dockerfile, Makefile
Depends on https://github.com/OCR-D/ocrd_anybaseocr/pull/89 (which in turn depends on https://github.com/OCR-D/ocropy/pull/2).
=> make Python 3.8 work

Makefile
There is no need for the additional directory "local" (which can
also be confused with "locale" on the same level).
=> Shorten path for SUB_VENV and define it only on the first make level

Makefile
Fixes:
- Depending on the host's DNS config and `/etc/docker/daemon.json`, networking during `docker build` may fail – see [here](https://medium.com/@faithfulanere/solved-docker-build-could-not-resolve-archive-ubuntu-com-apt-get-fails-to-install-anything-9ea4dfdcdcf2).
Updates:
- OCR-D/ocrd_anybaseocr#92
- bertsky/ocrd_detectron2@5bb90b18343393eaff9ab7874ace5b5bc6dcc22d
- OCR-D/ocrd_fileformat#38
- UB-Mannheim/ocrd_pagetopdf#19
- OCR-D/ocrd_segment@c523b8c
=> Fix docker network

.github/workflows/makedocker.yml, Dockerfile, Makefile
The new GitHub action currently allows maintainers to select git branch, Ubuntu version, Python version, docker image variant and upload to docker.io yes/no when it is run on demand.
By default it builds the `minimum` docker image on Ubuntu 18.04 with Python 3.6 and does not upload to docker.io.
=> Update Dockerfile, Makefile and GitHub action for Docker images

.gitmodules, Makefile, README.md
I suggest removing the now obsolete `sbb-textline-detector` (superseded by `Eynollah` which is already part of `ocrd_all`). 
I hope I have caught all places.
=> Remove sbb-textline-detector

Makefile
=> Disable modules which require old tensorflow-gpu unless it is available

Makefile, README.md
This adapts to https://github.com/OCR-D/ocrd_tesserocr/pull/187, which will be integrated with https://github.com/OCR-D/ocrd_all/pull/335, on the data/model side: `install-tesseract` and `install-tesseract-models` used to be split between OCR-D resource location and Tesseract tessdata prefix. Since this has become one again, there is no need for elaborate duplication and customization. We simply let the processor and resmgr use the compile-time tessdata/module dir, which is based on the venv as prefix.
Also updates some of the executable lists of other modules.
Proposed course of action: merge this branch into #335 (after additional fixes to core have been merged there).
=> tessdata: only use prefix/module dir

Makefile
(This change was broken: pip check did already run once per venv, but the sub-venv is not always available, e.g. in [minimum](https://email.circleci.com/c/eJxEjs1qtDAYRq_mdRcxUaNZuJjvc6R00UKh6yEmUd9OfiTG-bv6UqbQ7cNzDkd3LRdtZjrKW96UomIiW7qxoLJq-KjpONYVawwVgpZ1VTSCTg0VGXb_4ufXy9t8fA2S3hw_enfp4yH_09SsgqpYw5akzRVGZQ2xZpbqTnxIOKGJ5EJJrRXnWrWCE70sj1tmuyWldYPyAGwANjxRhbkKDtgwL8CG9_8fpAc2BBX1SVoLbKC0KaAc9uROSrpV4uyh7K8hnicbrmSSaI0Gxn8OzmjcHZS9cRLt77iFPSoDZf-sUzJh8FnsNqmW3W_nO1QF-ilEJxOe890jsQbXB865Nt8BAAD__xeeaco), so recursion is cleaner.)
This reverts commit 572ca369c367e3a932a957edd509f4a37c778303.
=> Revert "Only run pip check once per virtual environment"

.circleci/config.yml, Makefile
this will settle the remaining CI failures (CircleCI cimg ships Python 3.10, so modules like ocrd_kraken and cor-asv-ann had been disabled)
=> avoid PYTHON_VERSION checks to disable modules in docker builds

Makefile
We should have activated this long ago. It's not a true smoke test, but at least we know whether the executable can be run at module level at all.
=> enable running --help for make check

Dockerfile
=> docker: user simpler bash prompt

Makefile
This avoids a confusing error message on macOS for example.
=> Suppress error message for missing apt-cache

Makefile
Python 3.10 and 3.11 now are supported by current kraken.
=> Build ocrd_kraken also for latest Python versions

Makefile
The build fails on macOS (see issue 89).
=> Disable ocrd_olena on macOS

Dockerfile
Backed by successful prior test of:
docker run --gpus all --rm -v ocrd-models:/models -e OCRD_METS_CACHING=1 -it docker.io/ocrd/all:maximum-cuda make -C /build test-cuda test-workflow
Perhaps we should also make that the default for native installations? For example, we could patch the venv's `activate` script here: https://github.com/OCR-D/ocrd_all/blob/700747559975bb6c2993fac256adfa22dd4d01e4/Makefile#L218
=> Docker: enable METS caching

Makefile
/bin/bash on macOS is too old (3.2.57), but can be replaced by a recent bash version from Homebrew.
=> Use first bash from PATH (allows running on macOS)

CHANGELOG.md
Updates core to v2.59.1 which includes the workflow endpoint, additional features for chunking and additional output formats for `ocrd workspace list-page`; fixing the file naming in the bagger; and the filtering by file group for `clone`, `zip bag` etc.
@stweil improved the `page2img` script in format-converters significantly.
@mikegerber did some house cleaning work on dinglehopper and ocrd_calamari
ocrd_pagetopdf should now work properly on MacOS and supports the METS Server.
workflow-configuration contains additional XSLT to detect ID clashes and add missing confidence values, supports pretty printing XML in the CLIs and supports the METS Server.
tesseract is also updated to the latest state in master.
<del>I will merge this tomorrow, let me know if I missed something.</del> I forgot …
=> :package: v2023-12-07

Makefile
`make all` did not build ocrd_tesserocr if it was started without a virtual Python environment because ocrd_tesserocr requires a venv for building.
=> Fix build for ocrd_tesserocr (fixes issue #420)

.github/workflows/makeall-linux.yaml, .github/workflows/makedocker.yml
The old versions cause a warning:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3, actions/setup-python@v4.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Update several GitHub actions

.circleci/config.yml, .github/workflows/makedocker.yml, Makefile
fixes #416 
fixes #417 
fixes #434 
fixes #427
=> Docker build staged

release.sh
With this PR, two additional aliases for docker tags:
* `maximum-YYYY-MM-dd -> maximum`
* `maximum-cuda-YYYY-MM-dd -> maximum-cuda`
The first one to enable users of the non-CUDA maximum version to use a date-based tag for reproducibility.
The second one for consistency.
=> release-dockerhub: create aliases maximum{,-cuda}-YYYY-MM-DD, fix #401

.circleci/config.yml, Dockerfile
Otherwise build fails with
```
#11 ERROR: cannot replace to directory /.../build/core/.git with file
```
I am not sure how we introduced this and this workaround is not pretty (`rm -rf /build/core/.git`) so if somebody has a better solution, I'd be happy to change it.
=> Dockerfile: remove /build/core/.git directory to overwrite with submodule link

.circleci/config.yml, .github/workflows/makedocker.yml, Dockerfile, Makefile
=> docker: avoid re-entering XDG aliasing commands

.circleci/config.yml, .gitmodules, CHANGELOG.md, Dockerfile, Makefile
Time for a new release!
Includes the just released v2.70.0 of OCR-D/core as well as Dockerfiles for most projects (ht @joschrew @bertsky for that effort), so we now have slim containers consistently.
Also includes a new processor `ocrd-page2alto-transform` that provides an OCR-D interface for https://github.com/OCR-D/page-to-alto directly, which is significantly faster than using it via `ocrd-fileformat-transform -P from-to 'page alto'`.
=> Update 2024 10 11

Dockerfile
This only happens if users are building with `docker build` directly instead of through `make docker*` so we only noticed now. Perhaps it would be wise to change the Dockerfile to not have a default for `OCRD_MODULES` to encourage users to use the Makefile (which among other things makes sure that submodules are checked out).
=> Dockerfile: default for OCRD_MODULES was outdated

.gitmodules, CHANGELOG.md, Makefile, README.md
With this PR, OCR-D/core is updated to version 3, which brings many improvements in the way processors work. While not all processors have been ported to make use of these improvements, most of the widely used ones are (cf. [this draft PR](https://github.com/OCR-D/ocrd_all/pull/454) by @bertsky tracking adoption) and those that are not can still be run with the older processing API.
ocrd_olena and ocrd_pagetopdf have been rewritten in Python and are now significantly faster and better tested.
ocrd_im6convert has been removed since that functionality is available in a better form in ocrd_wrap's `ocrd-preprocess-image`.
sbb_binarization has also been dropped, as that functionality has been merged into eynollah and remains available as `ocrd-sbb-binarize` from there.
=> Release 2025 04 07
